region = "ap-northeast-1"
env = "dev"
state_bucket = "tfstate-pepese"
state_key = "sample/dev/ec2/terraform.tfstate"
state_key_vpc = "sample/dev/vpc/terraform.tfstate"
state_key_lb = "sample/dev/lb/terraform.tfstate"
ami = "ami-0992fc94ca0f1415a"
instance_type = "t3.nano"