system            = "sample"
region            = "ap-northeast-1"
env               = "dev"
state_bucket      = "tfstate-pepese"
state_key_self    = "sample/dev/lb/terraform.tfstate"
state_key_network = "sample/dev/network/terraform.tfstate"